// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('clarochk', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('clarochk', async function() {
    await driver.get("https://miclaroapp.com.co/")
    await driver.manage().window().setRect({ width: 1382, height: 736 })
    {
      const element = await driver.findElement(By.css(".resizehight"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    await driver.findElement(By.css(".cgray:nth-child(2)")).click()
    await driver.findElement(By.css(".pl15")).click()
    await driver.findElement(By.css(".pl15")).sendKeys("ship047j@gmail.com")
    await driver.findElement(By.id("myPassword")).click()
    await driver.findElement(By.id("myPassword")).sendKeys("Sdvsf123$")
    await driver.switchTo().frame(2)
    await driver.findElement(By.css(".recaptcha-checkbox-border")).click()
    await driver.switchTo().defaultContent()
    await driver.findElement(By.id("login")).click()
    await driver.findElement(By.css(".dropdown")).click()
    await driver.findElement(By.css(".line-item > .ng-binding")).click()
    await driver.findElement(By.xpath("(//p[@id=\'msj\'])[2]")).click()
    await driver.findElement(By.css(".tambienpuedes-card:nth-child(4) > .m0")).click()
    await driver.findElement(By.css(".p7")).click()
    await driver.findElement(By.css(".p7")).sendKeys("3135987887")
    await driver.findElement(By.css(".mt10 > .bgbluelight")).click()
    await driver.findElement(By.css(".p7")).click()
    await driver.findElement(By.css(".p7")).click()
    {
      const element = await driver.findElement(By.css(".p7"))
      await driver.actions({ bridge: true}).doubleClick(element).perform()
    }
    await driver.findElement(By.css(".p7")).sendKeys("3126352922")
    await driver.findElement(By.css(".mt10 > .bgbluelight")).click()
  })
})
